Updating some constraints for Macos
I got the error: 
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
It is fixed by calling the build query like:
nix --extra-experimental-features nix-command -f default.nix plutus.haskell.packages.plutus-core.components.library
So I added this as a third note in the 9th step.
Also plutus-playground.client, plutus-playground.client, etc, was moved to the plutus-apps repository: https://github.com/input-output-hk/plutus-apps so I updated that